### ISSUE TITLE
Where can I find the original data?

### ISSUE THREAD

**Issue by DoojinBaek** [ryi06/NetTIME#3]
Hi, Thank you for sharing your great work!

I’m trying to reproduce the results in the paper because I’m interested in MTL for TF binding prediction.
I can access the example datasets, but the original dataset you used for the experiments is hard to find.

You mentioned that the dataset is in the Supplementary Data section, but there is no such section in the document.

Would you let me know where I can get the original data you used for the research?

Thanks in advance!

**Comment by ryi06** [comment]
Hello DoojinBaek,

Thanks for reaching out. You can find the supplementary data on [BioRxiv](https://www.biorxiv.org/content/10.1101/2021.05.29.446316v2.supplementary-material). We're still finalizing a couple of things about our model. For now, you can access the oroginal dataset [here](https://drive.google.com/drive/folders/1WWbqmg4d3FO4ZJwrOLm7gxv4Ep7UZdIo?usp=sharing).
